### ISSUE TITLE
Sync with upstream

### ISSUE THREAD

**Issue by balloob** [NabuCasa/esp-web-flasher#104]
- https://github.com/adafruit/Adafruit_WebSerial_ESPTool/pull/22
   - [ ] Improves the stubgen.py to automatically download and parse esptool.py for the stubs
   - [ ] Updates the stubs to the latest versions
   - [ ] Organizes the Chip differences in one place to make adding new chips easier
   - [ ] Fixed writeRegister()
   - [ ] Added some new features such as runSpiflashCommand() and compressed flashing
      - Note: we already had compress flashing, and it's similar. Let's adopt their approach to make it easier to keep in sync.
   - [ ] rename sendCommand to command() to be more inline with esptool.py
   - [ ] Fixes an issue with debugging where debug messages were not showing properly
      - Note: we have a different debug set up right now. Maybe we should sync up again?

**Comment by balloob** [comment]
Now that upstream has caught up on compression, it might be worth to explore the set of changes necessary to take current upstream and export it as an NPM package, instead of expanding our version with their latest changes, which have diverged some bits. The goal of this fork is to do the least amount of work to get their version NPM installable.

**Comment by balloob** [comment]
I've taken a look at if it's feasible to bundle and package up upstream. From a quick glance there are a few minor issues. Documented it with patch in [this branch](https://github.com/NabuCasa/esp-web-flasher/tree/export-patch/export).

Last time Adafruit was not interested in making it a package, however I think that some of the discovered issues could maybe be fixed upstreamed.

**Comment by makermelissa** [comment]
Upstream is now archived, but some of the improvements from there could be added here. :)
