### ISSUE TITLE
[Feature Request] Flash mode and MCU clock

### ISSUE THREAD

**Issue by Jason2866** [NabuCasa/esp-web-flasher#54]
Maybe i missed that but there is no possibility to set Flash Mode (QIO, QOUT, DIO and DOUT)
nor the MCU clock frequency.

**Comment by balloob** [comment]
Based on my understanding from https://github.com/NabuCasa/esp-web-flasher/issues/83 you need to set this in the image itself.

**Comment by Jason2866** [comment]
Closing since using one binary files now which have all "on board" (possible since no patching is done anymore to the files).
