### ISSUE TITLE
Detect more chip families

### ISSUE THREAD

**Issue by balloob** [NabuCasa/esp-web-flasher#8]
Looks like other chips can be detected too https://github.com/espressif/esptool/blob/master/esptool.py#L351

**Comment by conradopoole** [comment]
#23 Includes new chip detection based on   CHIP_DETECT_MAGIC_REG_ADDR register that can handle more chip types. Note that all available now on esptool are part of that PR, but there are many places in the rest of the code that do not take those other chips into account. There are differences in certain registry addresses is some of them.
