### ISSUE TITLE
Support for ESP32-S3

### ISSUE THREAD

**Issue by Jason2866** [NabuCasa/esp-web-flasher#96]
since it is already supported in Arduino ESP32 git branch https://github.com/espressif/arduino-esp32/tree/esp32-s3-support
and a official release for will be soon done.

**Comment by balloob** [comment]
Adding it should be similar to how we added C3 support in #26.

Also looks like upstream already supports it https://github.com/adafruit/Adafruit_WebSerial_ESPTool/tree/main/stubs

**Comment by Jason2866** [comment]
@balloob  Thx!
Can you publish to NPM? It seems the github action for did not run
